const projects = [
  {
    id: 1,
    folder: "yazlik-villa-mutfak-silivri",
    title: "Yazlık Villa Mutfağı",
    location: "Silivri, İstanbul",
    category: "Mutfak",
    designer: "GATA",
    year: "Ocak 2024",
    status: "Tamamlandı",
    cover: "cover.webp",
    slides: [
      "slide-1.webp",
      "slide-2.webp",
      "slide-3.webp"
    ]
  },
  {
    id: 2,
    folder: "karkas-restaurant-emirgan",
    title: "Karkas Restaurant",
    location: "Sarıyer, İstanbul",
    category: "Restaurant",
    designer: "GATA",
    year: "Haziran 2024",
    status: "Tamamlandı",
    cover: "cover.webp",
    slides: [
      "slide-1.webp",
      "slide-2.webp",
      "slide-3.webp",
      "slide-4.webp",
      "slide-5.webp",
      "slide-6.webp",
      "slide-7.webp",
      "slide-8.webp",
      "slide-9.webp",
      "slide-10.webp",
      "slide-11.webp",
      "slide-12.webp",
      "slide-13.webp",
      "slide-14.webp",
      "slide-15.webp",
      "slide-16.webp",
      "slide-17.webp"
    ]
  },
  {
    id: 3,
    folder: "karaca-deneyim-merkezi-bakirkoy",
    title: "Karaca Deneyim Merkezi",
    location: "Bakırköy, İstanbul",
    category: "Mağaza, Sergileme",
    designer: "GATA",
    year: "Kasım 2023",
    status: "Tamamlandı",
    cover: "cover.webp",
    slides: [
      "slide-1.webp",
      "slide-2.webp",
      "slide-3.webp",
      "slide-4.webp",
      "slide-5.webp",
      "slide-6.webp",
      "slide-7.webp",
      "slide-8.webp",
      "slide-9.webp",
      "slide-10.webp",
      "slide-11.webp",
      "slide-12.webp",
      "slide-13.webp",
      "slide-14.webp",
      "slide-15.webp"
    ]
  },
  {
    id: 4,
    folder: "erenkoy-bloklar-lobi-tasarimi-erenkoy",
    title: "Erenköy Bloklar Lobi Tasarımı",
    location: "Erenköy, İstanbul",
    category: "Lobi, Giriş/Karşılama Alanı",
    designer: "GATA",
    year: "Aralık 2023",
    status: "Tamamlandı",
    cover: "cover.webp",
    slides: [
      "slide-1.webp",
      "slide-2.webp",
      "slide-3.webp",
      "slide-4.webp"
    ]
  },
  {
    id: 5,
    folder: "etiox-diyetisyen-klinigi-mersin",
    title: "Etioks Diyetisyen Kliniği",
    location: "Mersin",
    category: "Klinik, Ofis",
    designer: "GATA",
    year: "Nisan 2025",
    status: "Tamamlandı",
    cover: "cover.webp",
    slides: [
      "slide-1.webp",
      "slide-2.webp",
      "slide-3.webp",
      "slide-4.webp",
      "slide-5.webp",
      "slide-6.webp",
      "slide-7.webp",
      "slide-8.webp",
      "slide-9.webp",
      "slide-10.webp",
      "slide-11.webp"
    ]
  },
  {
    id: 6,
    folder: "cinarkoy-konut-cekmekoy",
    title: "Çınarköy Konut Projesi",
    location: "Çekmeköy, İstanbul",
    category: "Konut, Barınma",
    designer: "GATA",
    year: "Temmuz 2023",
    status: "Tamamlandı",
    cover: "cover.webp",
    slides: [
      "slide-1.webp",
      "slide-2.webp",
      "slide-3.webp",
      "slide-4.webp",
      "slide-5.webp",
      "slide-6.webp",
      "slide-7.webp",
      "slide-8.webp",
      "slide-9.webp",
      "slide-10.webp",
      "slide-11.webp",
      "slide-12.webp",
      "slide-13.webp",
      "slide-14.webp",
      "slide-15.webp",
      "slide-16.webp",
      "slide-17.webp",
      "slide-18.webp",
      "slide-19.webp",
      "slide-20.webp",
      "slide-21.webp",
      "slide-22.webp",
      "slide-23.webp",
      "slide-24.webp",
      "slide-25.webp",
      "slide-26.webp",
      "slide-27.webp",
      "slide-28.webp",
      "slide-29.webp",
      "slide-30.webp",
      "slide-31.webp",
      "slide-32.webp",
      "slide-33.webp",
      "slide-34.webp",
      "slide-35.webp",
      "slide-36.webp"
    ]
  },
  {
    id: 7,
    folder: "bo-villa-bahcesehir",
    title: "BO Villa Projesi",
    location: "Bahçeşehir, İstanbul",
    category: "Konut, Barınma",
    designer: "GATA",
    year: "Nisan 2024",
    status: "Tamamlandı",
    cover: "cover.webp",
    slides: [
      "slide-1.webp",
      "slide-2.webp",
      "slide-3.webp",
      "slide-4.webp",
      "slide-5.webp",
      "slide-6.webp",
      "slide-7.webp",
      "slide-8.webp",
      "slide-9.webp",
      "slide-10.webp",
      "slide-11.webp",
      "slide-12.webp",
      "slide-13.webp",
      "slide-14.webp",
      "slide-15.webp",
      "slide-16.webp"
    ]
  },
  {
    id: 8,
    folder: "acarkent-konut",
    title: "Acarkent Konut Projesi",
    location: "Beykoz, İstanbul",
    category: "Konut, Barınma",
    designer: "GATA",
    year: "Ekim 2023",
    status: "Tamamlandı",
    cover: "cover.webp",
    slides: [
      "slide-1.webp",
      "slide-2.webp",
      "slide-3.webp",
      "slide-4.webp",
      "slide-5.webp",
      "slide-6.webp",
      "slide-7.webp",
      "slide-8.webp",
      "slide-9.webp",
      "slide-10.webp",
      "slide-11.webp",
      "slide-12.webp",
      "slide-13.webp",
      "slide-14.webp",
      "slide-15.webp",
      "slide-16.webp",
      "slide-17.webp"
    ]
  }
];

