const projects = [
  {
    id: 1,
    folder: "yazlik-villa-mutfak-silivri",
    title: "Yazlık Villa Mutfağı",
    location: "Silivri, İstanbul",
    category: "Mutfak",
    designer: "GATA",
    year: "Ocak 2024",
    status: "Tamamlandı",
    cover: "cover.jpg",
    slides: [
      "slide-1.jpg",
      "slide-2.jpg",
      "slide-3.jpg"
    ]
  },
  {
    id: 2,
    folder: "karkas-restaurant-emirgan",
    title: "Karkas Restaurant",
    location: "Sarıyer, İstanbul",
    category: "Restaurant",
    designer: "GATA",
    year: "Haziran 2024",
    status: "Tamamlandı",
    cover: "cover.jpg",
    slides: [
      "slide-1.jpg",
      "slide-2.jpg",
      "slide-3.jpg",
      "slide-4.jpg",
      "slide-5.jpg",
      "slide-6.jpg",
      "slide-7.jpg",
      "slide-8.jpg",
      "slide-9.jpg",
      "slide-10.jpg",
      "slide-11.jpg",
      "slide-12.jpg",
      "slide-13.jpg",
      "slide-14.jpg",
      "slide-15.jpg",
      "slide-16.jpg",
      "slide-17.jpg"
    ]
  },
  {
    id: 3,
    folder: "karaca-deneyim-merkezi-bakirkoy",
    title: "Karaca Deneyim Merkezi",
    location: "Bakırköy, İstanbul",
    category: "Mağaza, Sergileme",
    designer: "GATA",
    year: "Kasım 2023",
    status: "Tamamlandı",
    cover: "cover.jpg",
    slides: [
      "slide-1.jpg",
      "slide-2.jpg",
      "slide-3.jpg",
      "slide-4.jpg",
      "slide-5.jpg",
      "slide-6.jpg",
      "slide-7.jpg",
      "slide-8.jpg",
      "slide-9.jpg",
      "slide-10.jpg",
      "slide-11.jpg",
      "slide-12.jpg",
      "slide-13.jpg",
      "slide-14.jpg",
      "slide-15.jpg"
    ]
  },
  {
    id: 4,
    folder: "erenkoy-bloklar-lobi-tasarimi-erenkoy",
    title: "Erenköy Bloklar Lobi Tasarımı",
    location: "Erenköy, İstanbul",
    category: "Lobi, Giriş/Karşılama Alanı",
    designer: "GATA",
    year: "Aralık 2023",
    status: "Tamamlandı",
    cover: "cover.jpg",
    slides: [
      "slide-1.jpg",
      "slide-2.jpg",
      "slide-3.jpg",
      "slide-4.jpg"
    ]
  },
  {
    id: 5,
    folder: "etiox-diyetisyen-klinigi-mersin",
    title: "Etioks Diyetisyen Kliniği",
    location: "Mersin",
    category: "Klinik, Ofis",
    designer: "GATA",
    year: "Nisan 2025",
    status: "Tamamlandı",
    cover: "cover.jpg",
    slides: [
      "slide-1.jpg",
      "slide-2.jpg",
      "slide-3.jpg",
      "slide-4.jpg",
      "slide-5.jpg",
      "slide-6.jpg",
      "slide-7.jpg",
      "slide-8.jpg",
      "slide-9.jpg",
      "slide-10.jpg",
      "slide-11.jpg"
    ]
  },
  {
    id: 6,
    folder: "cinarkoy-konut-cekmekoy",
    title: "Çınarköy Konut Projesi",
    location: "Çekmeköy, İstanbul",
    category: "Konut, Barınma",
    designer: "GATA",
    year: "Temmuz 2023",
    status: "Tamamlandı",
    cover: "cover.jpg",
    slides: [
      "slide-1.jpg",
      "slide-2.jpg",
      "slide-3.jpg",
      "slide-4.jpg",
      "slide-5.jpg",
      "slide-6.jpg",
      "slide-7.jpg",
      "slide-8.jpg",
      "slide-9.jpg",
      "slide-10.jpg",
      "slide-11.jpg",
      "slide-12.jpg",
      "slide-13.jpg",
      "slide-14.jpg",
      "slide-15.jpg",
      "slide-16.jpg",
      "slide-17.jpg",
      "slide-18.jpg",
      "slide-19.jpg",
      "slide-20.jpg",
      "slide-21.jpg",
      "slide-22.jpg",
      "slide-23.jpg",
      "slide-24.jpg",
      "slide-25.jpg",
      "slide-26.jpg",
      "slide-27.jpg",
      "slide-28.jpg",
      "slide-29.jpg",
      "slide-30.jpg",
      "slide-31.jpg",
      "slide-32.jpg",
      "slide-33.jpg",
      "slide-34.jpg",
      "slide-35.jpg",
      "slide-36.jpg"
    ]
  },
  {
    id: 7,
    folder: "bo-villa-bahcesehir",
    title: "BO Villa Projesi",
    location: "Bahçeşehir, İstanbul",
    category: "Konut, Barınma",
    designer: "GATA",
    year: "Nisan 2024",
    status: "Tamamlandı",
    cover: "cover.jpg",
    slides: [
      "slide-1.jpg",
      "slide-2.jpg",
      "slide-3.jpg",
      "slide-4.jpg",
      "slide-5.jpg",
      "slide-6.jpg",
      "slide-7.jpg",
      "slide-8.jpg",
      "slide-9.jpg",
      "slide-10.jpg",
      "slide-11.jpg",
      "slide-12.jpg",
      "slide-13.jpg",
      "slide-14.jpg",
      "slide-15.jpg",
      "slide-16.jpg"
    ]
  },
  {
    id: 8,
    folder: "acarkent-konut",
    title: "Acarkent Konut Projesi",
    location: "Beykoz, İstanbul",
    category: "Konut, Barınma",
    designer: "GATA",
    year: "Ekim 2023",
    status: "Tamamlandı",
    cover: "cover.jpg",
    slides: [
      "slide-1.jpg",
      "slide-2.jpg",
      "slide-3.jpg",
      "slide-4.jpg",
      "slide-5.jpg",
      "slide-6.jpg",
      "slide-7.jpg",
      "slide-8.jpg",
      "slide-9.jpg",
      "slide-10.jpg",
      "slide-11.jpg",
      "slide-12.jpg",
      "slide-13.jpg",
      "slide-14.jpg",
      "slide-15.jpg",
      "slide-16.jpg",
      "slide-17.jpg"
    ]
  }
];

